### PR TITLE
Added support for NRK Radio

### PR DESCRIPTION
**Pull request by kristianj**

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hi there, thank you for contributing! I see that you have conflicts in your Readme file, would you be willing to resolve them?

**Comment by kristianj** [comment]
Ok, made a new commit now 👍

**Comment by vinyldarkscratch** [comment]
Greatly appreciated, thank you!  😄

**Comment by feedbee** [comment]
Could you consider making few more fixes, please?

1. Service names in README are alphabetically ordered.
2. Is it possible for rev and next buttons to switch between podcasts, not seek for ±30 secs?
3. Can you rewrite the code to use [shared-injection.js](https://github.com/borismus/keysocket/blob/master/extension/shared-injection.js)? It's less resource consuming and faster because it uses messaging on events, and injection only at startup? Your code uses injection on every event.

Thatks.

**Comment by kristianj** [comment]
Have tried to fix this now:
1. Service names are now in alphabetical order
2. Removed support for these buttons - this radio player doesn't have next/prev functionality
3. Have rewritten to use the shared-injection.js functionality now

**Comment by feedbee** [comment]
Merged, thank you. NRK Radio will be supported after next extension update.

**Pull request merged**
