### PR TITLE
Click helper

### PR DESCRIPTION
**Pull request by nemchik**
This is finally ready to go!

I went down the list and tested every single player, but due to limitations (subscriptions, country/region, etc) here is a list of players I was unable to test;
deezer
dsaudio5
musicchoice
ok.ru
overcast
plex
tidal
tracksflow
vkontakte
xboxmusic
xiami
yandex

These last two were broken before any changes I made. I will submit a separate RP to fix these, but at least let's get them merged with the new function.
amazon
slacker

### CODE REVIEW

**Comment by borismus** [comment]
Thanks Eric. Why were you unable to test a bunch? I'm uncomfortable committing such a huge change without very thorough testing.

**Comment by nemchik** [comment]
Some of them require subscriptions, others are limited to access only from users connecting in certain countries.

**Comment by nemchik** [comment]
Would you like me to submit a PR with only the players I have confirmed working?

Doing this would mean that the players I cannot access will still use the simulateClick function until someone else tests and converts them.

**Comment by borismus** [comment]
Yes, good idea. You can implement simulateClick() which takes an element or
a selector as an argument, as well. A less sweeping change would make me
feel more comfortable.

**Comment by nemchik** [comment]
You mean like this?
```
function simulateSelectorClick(element, frame) {
    var elementSelected;
    if (typeof frame !== 'undefined') {
      elementSelected = document.querySelector(frame).contentDocument.querySelector(element);
    } else {
      elementSelected = document.querySelector(element);
    }
    if (typeof elementSelected[0] !== 'undefined') elementSelected = elementSelected[0];
    return simulateClick(elementSelected);
}
```

**Comment by nemchik** [comment]
Nevermind I think I know what you mean. One function that can do the current AND the proposed behaviour without needing to recode any of the sockets.

**Comment by borismus** [comment]
Yes affirmative

**Comment by nemchik** [comment]
Closing this PR in favor of #107

**Comment by borismus** [comment]
No need to close and open these. You can iterate on the same pull request.

**Comment by nemchik** [comment]
I don't know how to do that, I'll have to look it up

**Pull request closed without merging**
