### PR TITLE
LinkedIn learning

### PR DESCRIPTION
**Pull request by coliff**
This adds support for LinkedIn Learning.

Play, Next and Previous all work correctly (tested with Apple wired keyboard on Windows 10 64-Bit with Chrome 68). Note that Pause does not work, I couldn't figure it out.. maybe someone else can?

### CODE REVIEW

**Comment by coliff** [comment]
thanks for the feedback @feedbee - I tried that locally and it didn't work... `:visible` isn't a valid CSS selector.. should it be something else?

**Comment by feedbee** [comment]
I tested it in developer tools. It worked. Ok, I'll check it with the add-on a bit later.

**Comment by feedbee** [comment]
@coliff, `.ssplayer-playing .ssplayer-pause-button, .ssplayer-paused .ssplayer-play-button` works. Just tried.

**Comment by coliff** [comment]
Great - I tested this too and it works for me. I need to update my PR to resolve the conflicts which I'll look to do tomorrow morning.

**Comment by coliff** [comment]
hey @feedbee sorry for the delay but the conflict is resolved now so I think this is good to merge for the next release. 👍

**Pull request merged**
