### PR TITLE
Adding STOP functionality

### PR DESCRIPTION
**Pull request by nemchik**
This solves borismus#64 but may need some cleanup. I have verified the functionality on Pandora, Spotify, SoundCloud, Google Music, and YouTube. Based on the success of the changes for these keysockets I made changes wherever I could see similarly available code in other KeySockets.

Also I am new to GIT so i'm sure this is not the easiest way to submit, just used the edit botton in the browser for each file. Sorry if this makes anything difficult.

And I apparently also included another commit in this pull request to do stuff with MouseEvent. Please feel free to somehow separate these.

### CODE REVIEW

**Comment by borismus** [comment]
I really don't think the stop button is present on many keyboards. Why not just pause? Also I have concerns about testing: have you tested on all of these music players?

**Comment by nemchik** [comment]
I only tested on the ones I listed in the commit message. For any of the ones I did not test, I saw that the play/pause function was actually a separate play and pause input determined by whether the music was actually playing or not. With that in mind, issuing the pause command in place of stop is the end goal of the issue i had created.

While there may not be many keyboard with a physical stop button there are plenty of gaming keyboards and other programs that allow hotkeys to be triggered by key combinations (like autohotkey) and using something like nircmd they can actually issue media key inputs (0xB2 for stop) and as such any user who prefers to do so can have a "stop button".

These changes are meant to add to user choice. If someone chooses to use the stop button (physical or otherwise) it will function as you would expect. The stop button should stop the music (in this case pause serves the same purpose by discontinuing the audio from being played) but not start it if pressed again like play/pause.

**Comment by nemchik** [comment]
I would be happy to test the other sites that I had submitted changes for, really I only tested the ones I actually use personally, but I have not added any new code, just copy/pasted existing code and left in the parts that instruct the extension to pause and removed the parts that play. The "isPlaying" logic was already in place for all of the sites except Google Play Music, Spotify, and SoundCloud, so really it wasnt difficult to copy the code and modify the logic.

**Comment by borismus** [comment]
I'd rather you figure out a way to reduce all of the copy-pasted logic. As
it stands, this makes the code pretty complex for a feature that very few
keyboards have.

**Comment by nemchik** [comment]
I can do that. Might be some time though. If you'd like to trash this set
of changes and i'll try and resubmit a new set (hopefully a bit more
organized as i'm learning GIT slowly).


--
Eric Nemchik
http://nemchik.com/

**Comment by nemchik** [comment]
Before I go rewrite all the keysockets can you tell me if this looks good?
keysocket-gmusic.js
```
function onKeyPress(key) {
    if(key === NEXT) {
        Button = document.querySelector('[data-id=forward]');
    } else if(key === PLAY) {
        Button = document.querySelector('[data-id=play-pause]');
    } else if(key === STOP) {
		Button = (document.querySelector('[data-id=play-pause].playing') != null) ? document.querySelector('[data-id=play-pause].playing') : null;
    } else if(key === PREV) {
        Button = document.querySelector('[data-id=rewind]');
    }
	simulateClick(Button);
}
```

**Comment by borismus** [comment]
Please stick to the JS style guide:
http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml. Your
variable name casing is a bit odd, etc.

Also, in terms of whether it's good or not -- depends on whether it works.
Unfortunately this sort of code is going to go constantly out of date as
these music services change their webpages.

**Comment by nemchik** [comment]
I've rewritten just about all of the  key socket js files and really tried
to standardize the code (almost like a template). It should match up with
the guidelines you linked. The way I've written it makes adding a stop
button much more clean and simple (two lines)

When I get back to my computer I'll try and get them up here for review.

Again I'm brand new with git, and I think I removed the fork that has all
the commits for this pull request. I think I still have access to the other
pull request I made with the mouse event commit, so I'll try to add the new
commits to that pull request.

**Pull request closed without merging**
