### PR TITLE
Add support for Subsonic

### PR DESCRIPTION
**Pull request by ALiangLiang**
Adding support for Subsonic. http://www.subsonic.org/pages/index.jsp
It's a media streamer uses JWPlayer.
Probably this is not the best way to do this, but it was the only way that I could get working.

### CODE REVIEW

**Comment by philosowaffle** [comment]
@ALiangLiang 

+1

I suggest one modification to ensure this also works for [Madsonic](http://beta.madsonic.org/pages/index.jsp) (fork of Subsonic).  The Madsonic webplayer will have the same url matchers as the Subsonic webplayer.

```javascript
function onKeyPress(key) {
  if (this.jwplayer) {
    if (key === NEXT) {

      // Subsonic impl
      var nextButton = document.querySelector('img[onclick="onNext(false)"]');

      // Madsonic impl
      if(!nextButton){
        nextButton = document.querySelector('a[onclick="onNext(false)"]');
      }

      simulateClick(nextButton);

    } else if (key === PLAY) {
      location.href = "javascript:window.jwplayer().play()";
    } else if (key === PREV) {

      // Subsonic impl
      var backButton = document.querySelector('img[onclick="onPrevious()"]');

       // Madsonic impl
      if(!backButton){
        backButton = document.querySelector('a[onclick="onPrevious()"]');
      }

      simulateClick(backButton);
    }
  }
}
```

**Comment by ALiangLiang** [comment]
Good idea! But I suggest you PR a independent Madsonic version. It's some differense between Subsonic and Madsonic. I think it's will more convenient to maintain.

**Comment by philosowaffle** [comment]
Madsonic uses the exact same matchers as Subsonic in the manifest.json file so I cannot create a separate Madsonic entry as it would conflict with Subsonic.  Also, I doubt any of these pull requests will get merged by the repo owner anyway.  I just created a [fork ](https://github.com/philosowaffle/keysocket) that includes some of the less popular music players so people can have the option of installing this plugin in developer mode if they so choose.

**Comment by vinyldarkscratch** [comment]
Hello, thanks for your contribution!  Sorry for such a long wait, this project is now maintained by another, and we're now working on closing all issues and PRs as much as possible.  ;)  I tested this out and have had no issues with it, would you be willing to fix the conflicts with the manifest file before we accept your PR?

**Pull request merged**
