### PR TITLE
Streamsquid.com support

### PR DESCRIPTION
**Pull request by jdf221**

### CODE REVIEW

**Comment by borismus** [comment]
Hi, I'm not sure streamsquid.com is a big enough player to build in custom support for.

See https://github.com/borismus/keysocket/pull/122 for more info about what I mean. I think this is the general direction this extension should go. WDYT?

**Comment by jdf221** [comment]
Ah ok, that seems like a much better idea than just adding sites individually.

**Comment by borismus** [comment]
The downside is that each site needs to implement it... Not sure if you know the devs of streamsquid.com?

**Comment by jdf221** [comment]
No I don't.

But I feel like some of the less popular sites would be up to implementing it, until it got more known we would more then likely have to contact most of them manually.

**Pull request closed without merging**
