### PR TITLE
Added support for www.supersport.com

### PR DESCRIPTION
**Pull request by ViGouRCanberra**
Added support for www.supersport.com
You need an active paid subscription for this service
Only play/Pause functionality is available on the website

### CODE REVIEW

**Comment by ViGouRCanberra** [comment]
I haven't updated the version number yet, because I didn't just want to assume 0.10.0.
Should I update to 0.10.0, or leave the version unchanged?

**Comment by feedbee** [comment]
Hello. Thank you for contributing. You don't need to update version, I'll do it myself just before release. But you should add SuperSport to the list of supported services in README.md.

**Comment by ViGouRCanberra** [comment]
I've added SuperSport as a supported service.

**Comment by ViGouRCanberra** [comment]
@feedbee Would it be possible to merge this PR yet?
I made a little mistake on my side and made this PR from my master, instead of a feature branch, so additional features I'd like to add will also have these changes.

**Comment by feedbee** [comment]
I've just merged this PR. New release will be published to store tomorrow.

**Comment by feedbee** [comment]
Published to Store. Will be available to users in 60 minutes.

**Pull request merged**
