### PR TITLE
Add Crunchyroll

### PR DESCRIPTION
**Pull request by aleppos**

### CODE REVIEW

**Comment by feedbee** [comment]
Hello, @aleppos. Thanks for contributing.

Have you tested your code? As I see, play/pause and stop functionality doesn't work.

**Comment by aleppos** [comment]
@feedbee I have tested from the browswer and it's working fine, maybe I am missing something else?

**Comment by feedbee** [comment]
OK, I just have retested it and see that it works. So, the plugin is almost ready for merge. To support new plugin system I've merged today earlier you should change plugin's code to something like:

```javascript
keySocket.init('crunchyroll', {
    "play-pause": function() {
        document.querySelector('#showmedia_video_player').togglePlayPause();
    },
    "prev": function() {
        location.href = document.querySelector("link[rel=prev]").getAttribute("href");
    },
    "next": function() {
        location.href = document.querySelector("link[rel=next]").getAttribute("href");
    },
    "stop": function() {
        document.querySelector('#showmedia_video_player').pauseVideo();
    }
});
```

As it's done, I'll be able to merge this PR and upload new release to store. Thanks!

**Comment by aleppos** [comment]
@feedbee I have add a new extenssion for Vimeo

**Comment by feedbee** [comment]
Please, read my comment below and apply it to both Crunchyroll and Vimeo plugins

**Comment by aleppos** [comment]
@feedbee  how I can apply it?

**Comment by feedbee** [comment]
Keysocket API have been changed since the time you've started. Read [README](https://github.com/borismus/keysocket#please-contribute) to check out the changes. There isn't `function onKeyPress()` any more, and in my comment abobe I've wrote how to use new API (`keySocket.init(...)`).

**Comment by aleppos** [comment]
@feedbee done.

**Comment by feedbee** [comment]
Publishes to Store as version 0.9.1

**Pull request merged**
