### PR TITLE
Update jango.com DOM references.

### PR DESCRIPTION
**Pull request by raztus**

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hi there, I see there's a lot more in this PR than just jango.com's DOM references being updated alone.  Furthermore, we are considering merging some of the PRs that were merged into this repository.  Would you be willing to separate your changes into a single PR?

**Comment by raztus** [comment]
You learn something new every day: originally this pull-request was for `raztus/keysocket:master` into `borismus/keysocket:master` with a single commit for jango.com. When I recently made changes to the master fork, including moving it to its own organization and merging in a bunch of other branches, the PR now reflects those changes. This is unexpected behavior in my book, as the pull request should have been tied to a series of commits, not to a branch in Github. Oh well.

I don't intend to fix anything on this PR, since I first submitted it nearly 2 years ago, and it sat here ever since. I will now close it. Any future work I do on this code will be under the `media-keys` organization.

**Comment by feedbee** [comment]
I fixed jango.com bindings in https://github.com/borismus/keysocket/pull/210. It's sad that you decided to work on separated fork.

**Comment by raztus** [comment]
Working on a separate fork should be viewed only as a healthy part of open source software.

However, the only reason I forked was because @borismus marked this repository as un-maintained. When I contacted him via email about becoming a collaborator, he seemed only willing to consider that under a plan to fully refactor the codebase, which I'm not interested in doing. If you @feedbee are now maintaining this project again, I'll contribute here.

**Comment by feedbee** [comment]
We plan to transfer repository to organization a little bit later. But now, yes, I took the role to care about this repo. So feel free to contribute, reaction will be comparably fast :)

I reviewed all code you've added to your repo and see that almost all of it is into waiting pull requests or already merged.

**Comment by vinyldarkscratch** [comment]
Personally, I've reviewed the code in the media-keys branch, and it makes me happy to see the effort you guys have put into the extension.  I'd love to see the code pulled into this repository, seeing the changes becoming a part of the official release.  :)

**Comment by raztus** [comment]
@vinyldarkscratch None of that is my work, nor the work of the "media-keys" organization (which I created then haven't yet pursued.) The majoriy came from feedbee's branch, which in-turn was mostly merges from other outstanding PRs. In other words, all the relevant work is still here on `borismus/keysocket`.

**Pull request closed without merging**
